BEGIN;

DROP TABLE IF EXISTS "category", "list", "link", "list_has_category", "category_has_lists";

CREATE TABLE "category"(
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" TEXT NOT NULL,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    "updated_at" TIMESTAMPTZ
);

CREATE TABLE "list"(

    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" TEXT NOT NULL,
    "position" INTEGER NOT NULL DEFAULT 0,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    "updated_at" TIMESTAMPTZ,
    "category_id" INTEGER NOT NULL REFERENCES "category"("id") ON DELETE CASCADE

);

CREATE TABLE "link"(
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "url" TEXT NOT NULL,
    "position" INTEGER NOT NULL DEFAULT 0,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    "updated_at" TIMESTAMPTZ,
    "list_id" INTEGER NOT NULL REFERENCES "list"("id") ON DELETE CASCADE
);


-- CREATE TABLE "category_has_lists"(
--     "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--     "list_id" INTEGER NOT NULL REFERENCES "list" ON DELETE CASCADE,
--     "category_id" INTEGER NOT NULL REFERENCES "category" ON DELETE CASCADE,
--     "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW()
-- );


INSERT INTO "category" ("id", "name")
VALUES
(1, 'Musique'),
(2, 'Vidéo'),
(3, 'Concert');

INSERT INTO "list" ("id", "name", "position", "category_id")
VALUES
(1, 'À écouter', 1, 1),
(2, 'À réécouter', 0, 1),
(3, 'À regarder', 0, 2),
(4, 'À acheter', 0, 3);

INSERT INTO "link" ("id", "url", "list_id", "position")
VALUES
(1, 'https://deezer.page.link/svcDETuGbBHyeAFG8', 1, 0),
(2, 'https://deezer.page.link/xTZroX7xSB3bFKph7', 2, 0),
(3, 'https://www.youtube.com/watch?v=wa-E3WlQcSE', 3, 0),
(4, 'https://www.sallepleyel.com/concerts-spectacles/metal-hard-rock/opeth_e734', 4, 0);

-- INSERT INTO "category_has_lists" ("category_id", "list_id")
-- VALUES
-- (1, 1),
-- (1, 2),
-- (2, 3),
-- (3, 4);

SELECT setval('list_id_seq', (SELECT MAX(id) from "list"));
SELECT setval('link_id_seq', (SELECT MAX(id) from "link"));
SELECT setval('category_id_seq', (SELECT MAX(id) from "category"));


COMMIT;