### service indisponible
GET http://localhost:5050/404


############################## CATEGORIES #############################

### récupération de tous les catégories
GET http://localhost:5050/categories

### création d'un catégories
POST http://localhost:5050/categories
Content-Type: application/x-www-form-urlencoded

name= Achats

### modification d'un catégories
PATCH http://localhost:5050/categories/4
Content-Type: application/x-www-form-urlencoded

name=Achats à faire

### suppression d'un catégories
DELETE http://localhost:5050/categories/4

## OBSLOLÈTE
### associer une liste à une catégorie
# POST http://localhost:5050/lists/1/categories
# Content-Type: application/x-www-form-urlencoded

# category_id=1

## OBSLOLÈTE
### dissocié une catégorie d'une liste
# DELETE http://localhost:5050/lists/1/categories/1

############################## LISTS #############################

### récupération de toutes les listes avec leurs liens
GET http://localhost:5050/lists

### récupération d'une liste avec ses liens
GET http://localhost:5050/lists/7

### création d'une liste dans une catégorie
POST http://localhost:5050/lists
Content-Type: application/x-www-form-urlencoded

name=Ma playlist
&position=1
&category_id=1

### modification d'une liste
PATCH http://localhost:5050/lists/7
Content-Type: application/x-www-form-urlencoded

name=J'aime pas
&position=1
&category_id=1

### suppression d'une liste
DELETE http://localhost:5050/lists/7

############################## LINKS #############################

### récupération de tous les liens d'une liste
GET http://localhost:5050/lists/1/links

### récupération d'un lien
GET http://localhost:5050/links/3

### création d'un lien
POST http://localhost:5050/links
Content-Type: application/x-www-form-urlencoded

url=https://deezer.page.link/2J1zM6rZyyp22VoS9
&list_id=1

### modification d'un lien
PATCH http://localhost:5050/links/5
Content-Type: application/x-www-form-urlencoded

url=https://deezer.page.link/eJVm3MQcZrDuN1GA7
&position=1

### suppression d'un lien
DELETE http://localhost:5050/links/5
