[[redirects]]
  from = "https://www.theodorebing.com/category/api/*"
  to = "https://thetree-thelink.herokuapp.com/:splat"
  status = 200
  force = true

[[redirects]]
  from = "https://www.theodorebing.com/api/*"
  to = "https://thetree-thelink.herokuapp.com/:splat"
  status = 200
  force = true

[[redirects]]
  from = "https://www.theodorebing.com/category/:splat"
  to = "https://www.theodorebing.com/:splat"
  status = 200
  force = true
